### ISSUE TITLE
Rails Recipe-Group-Capstone

### ISSUE THREAD

**Issue by ibugithub** [MarcoDDM/recipe-app#12]
Rails Recipe-Group-Capstone:
[Project Link] (https://github.com/MarcoDDM/recipe-app/projects/1)

Team members:
We have 2 members in our group project.
Team Member 1: Ibrahim
Team Member 2: Marco

We have assigned all the tasks equally to all the team members manually.
As we have 2 members in the group we didn't add the tasks of member 3.

**Comment by frank1738** [comment]
Hi Team, 

You can go ahead with your project
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/11ISwbgCxEzMyY/giphy.gif"/>

## Highlights

✅ Tasks are setup and assigned properly👍 

## Optional suggestions

N/.A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MarcoDDM** [comment]
Thank you
